//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.03 at 03:30:34 PM EDT 
//


package com.intuit.sb.cdm.v2;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Holds credit-card transaction response information from a merchant account service, but not any credit card or payment request information - see CreditChargeInfo
 * 
 * <p>Java class for CreditChargeResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditChargeResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CCTransId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResultCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ResultMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MerchantAcctNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardSecurityCodeMatch" type="{http://www.intuit.com/sb/cdm/v2}CCSecurityCodeMatchEnum" minOccurs="0"/>
 *         &lt;element name="AuthCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AvsStreet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AvsZip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SecurityCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReconBatchId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PaymentGroupingCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="TxnAuthorizationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="TxnAuthorizationStamp" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ClientTransID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditChargeResponse", propOrder = {
    "ccTransId",
    "status",
    "resultCode",
    "resultMsg",
    "merchantAcctNum",
    "cardSecurityCodeMatch",
    "authCode",
    "avsStreet",
    "avsZip",
    "securityCode",
    "reconBatchId",
    "paymentGroupingCode",
    "txnAuthorizationTime",
    "txnAuthorizationStamp",
    "clientTransID"
})
public class CreditChargeResponse
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CCTransId")
    protected String ccTransId;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "ResultCode")
    protected BigInteger resultCode;
    @XmlElement(name = "ResultMsg")
    protected String resultMsg;
    @XmlElement(name = "MerchantAcctNum")
    protected String merchantAcctNum;
    @XmlElement(name = "CardSecurityCodeMatch")
    protected CCSecurityCodeMatchEnum cardSecurityCodeMatch;
    @XmlElement(name = "AuthCode")
    protected String authCode;
    @XmlElement(name = "AvsStreet")
    protected String avsStreet;
    @XmlElement(name = "AvsZip")
    protected String avsZip;
    @XmlElement(name = "SecurityCode")
    protected String securityCode;
    @XmlElement(name = "ReconBatchId")
    protected String reconBatchId;
    @XmlElement(name = "PaymentGroupingCode")
    protected BigInteger paymentGroupingCode;
    @XmlElement(name = "TxnAuthorizationTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar txnAuthorizationTime;
    @XmlElement(name = "TxnAuthorizationStamp")
    protected BigInteger txnAuthorizationStamp;
    @XmlElement(name = "ClientTransID")
    protected String clientTransID;

    /**
     * Gets the value of the ccTransId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCTransId() {
        return ccTransId;
    }

    /**
     * Sets the value of the ccTransId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCTransId(String value) {
        this.ccTransId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResultCode(BigInteger value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the resultMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultMsg() {
        return resultMsg;
    }

    /**
     * Sets the value of the resultMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultMsg(String value) {
        this.resultMsg = value;
    }

    /**
     * Gets the value of the merchantAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantAcctNum() {
        return merchantAcctNum;
    }

    /**
     * Sets the value of the merchantAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantAcctNum(String value) {
        this.merchantAcctNum = value;
    }

    /**
     * Gets the value of the cardSecurityCodeMatch property.
     * 
     * @return
     *     possible object is
     *     {@link CCSecurityCodeMatchEnum }
     *     
     */
    public CCSecurityCodeMatchEnum getCardSecurityCodeMatch() {
        return cardSecurityCodeMatch;
    }

    /**
     * Sets the value of the cardSecurityCodeMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCSecurityCodeMatchEnum }
     *     
     */
    public void setCardSecurityCodeMatch(CCSecurityCodeMatchEnum value) {
        this.cardSecurityCodeMatch = value;
    }

    /**
     * Gets the value of the authCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * Sets the value of the authCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthCode(String value) {
        this.authCode = value;
    }

    /**
     * Gets the value of the avsStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvsStreet() {
        return avsStreet;
    }

    /**
     * Sets the value of the avsStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvsStreet(String value) {
        this.avsStreet = value;
    }

    /**
     * Gets the value of the avsZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvsZip() {
        return avsZip;
    }

    /**
     * Sets the value of the avsZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvsZip(String value) {
        this.avsZip = value;
    }

    /**
     * Gets the value of the securityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * Sets the value of the securityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityCode(String value) {
        this.securityCode = value;
    }

    /**
     * Gets the value of the reconBatchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReconBatchId() {
        return reconBatchId;
    }

    /**
     * Sets the value of the reconBatchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReconBatchId(String value) {
        this.reconBatchId = value;
    }

    /**
     * Gets the value of the paymentGroupingCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaymentGroupingCode() {
        return paymentGroupingCode;
    }

    /**
     * Sets the value of the paymentGroupingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaymentGroupingCode(BigInteger value) {
        this.paymentGroupingCode = value;
    }

    /**
     * Gets the value of the txnAuthorizationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTxnAuthorizationTime() {
        return txnAuthorizationTime;
    }

    /**
     * Sets the value of the txnAuthorizationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTxnAuthorizationTime(XMLGregorianCalendar value) {
        this.txnAuthorizationTime = value;
    }

    /**
     * Gets the value of the txnAuthorizationStamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTxnAuthorizationStamp() {
        return txnAuthorizationStamp;
    }

    /**
     * Sets the value of the txnAuthorizationStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTxnAuthorizationStamp(BigInteger value) {
        this.txnAuthorizationStamp = value;
    }

    /**
     * Gets the value of the clientTransID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientTransID() {
        return clientTransID;
    }

    /**
     * Sets the value of the clientTransID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientTransID(String value) {
        this.clientTransID = value;
    }

}
