//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.03 at 03:30:34 PM EDT 
//


package com.intuit.sb.cdm.v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.intuit.sb.cdm.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Employee_QNAME = new QName("http://www.intuit.com/sb/cdm/v2", "Employee");
    private final static QName _Organization_QNAME = new QName("http://www.intuit.com/sb/cdm/v2", "Organization");
    private final static QName _CustomFieldDefinition_QNAME = new QName("http://www.intuit.com/sb/cdm/v2", "CustomFieldDefinition");
    private final static QName _CustomField_QNAME = new QName("http://www.intuit.com/sb/cdm/v2", "CustomField");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.intuit.sb.cdm.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TxnGeneric }
     * 
     */
    public TxnGeneric createTxnGeneric() {
        return new TxnGeneric();
    }

    /**
     * Create an instance of {@link SalesTerm }
     * 
     */
    public SalesTerm createSalesTerm() {
        return new SalesTerm();
    }

    /**
     * Create an instance of {@link IdType }
     * 
     */
    public IdType createIdType() {
        return new IdType();
    }

    /**
     * Create an instance of {@link ModificationMetaData }
     * 
     */
    public ModificationMetaData createModificationMetaData() {
        return new ModificationMetaData();
    }

    /**
     * Create an instance of {@link NameValue }
     * 
     */
    public NameValue createNameValue() {
        return new NameValue();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link ShipMethod }
     * 
     */
    public ShipMethod createShipMethod() {
        return new ShipMethod();
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link InvoiceHeader }
     * 
     */
    public InvoiceHeader createInvoiceHeader() {
        return new InvoiceHeader();
    }

    /**
     * Create an instance of {@link InvoiceLine }
     * 
     */
    public InvoiceLine createInvoiceLine() {
        return new InvoiceLine();
    }

    /**
     * Create an instance of {@link TaxLine }
     * 
     */
    public TaxLine createTaxLine() {
        return new TaxLine();
    }

    /**
     * Create an instance of {@link SalesTaxCode }
     * 
     */
    public SalesTaxCode createSalesTaxCode() {
        return new SalesTaxCode();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link RoleBase }
     * 
     */
    public RoleBase createRoleBase() {
        return new RoleBase();
    }

    /**
     * Create an instance of {@link PhysicalAddress }
     * 
     */
    public PhysicalAddress createPhysicalAddress() {
        return new PhysicalAddress();
    }

    /**
     * Create an instance of {@link TelephoneNumber }
     * 
     */
    public TelephoneNumber createTelephoneNumber() {
        return new TelephoneNumber();
    }

    /**
     * Create an instance of {@link WebSiteAddress }
     * 
     */
    public WebSiteAddress createWebSiteAddress() {
        return new WebSiteAddress();
    }

    /**
     * Create an instance of {@link EmailAddress }
     * 
     */
    public EmailAddress createEmailAddress() {
        return new EmailAddress();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link JobInfo }
     * 
     */
    public JobInfo createJobInfo() {
        return new JobInfo();
    }

    /**
     * Create an instance of {@link Check }
     * 
     */
    public Check createCheck() {
        return new Check();
    }

    /**
     * Create an instance of {@link CheckHeader }
     * 
     */
    public CheckHeader createCheckHeader() {
        return new CheckHeader();
    }

    /**
     * Create an instance of {@link CheckLine }
     * 
     */
    public CheckLine createCheckLine() {
        return new CheckLine();
    }

    /**
     * Create an instance of {@link Parties }
     * 
     */
    public Parties createParties() {
        return new Parties();
    }

    /**
     * Create an instance of {@link Party }
     * 
     */
    public Party createParty() {
        return new Party();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link AccountRef }
     * 
     */
    public AccountRef createAccountRef() {
        return new AccountRef();
    }

    /**
     * Create an instance of {@link VendorRef }
     * 
     */
    public VendorRef createVendorRef() {
        return new VendorRef();
    }

    /**
     * Create an instance of {@link BillPayment }
     * 
     */
    public BillPayment createBillPayment() {
        return new BillPayment();
    }

    /**
     * Create an instance of {@link BillPaymentHeader }
     * 
     */
    public BillPaymentHeader createBillPaymentHeader() {
        return new BillPaymentHeader();
    }

    /**
     * Create an instance of {@link BillPaymentLine }
     * 
     */
    public BillPaymentLine createBillPaymentLine() {
        return new BillPaymentLine();
    }

    /**
     * Create an instance of {@link CreditCardCredit }
     * 
     */
    public CreditCardCredit createCreditCardCredit() {
        return new CreditCardCredit();
    }

    /**
     * Create an instance of {@link CreditCardCreditHeader }
     * 
     */
    public CreditCardCreditHeader createCreditCardCreditHeader() {
        return new CreditCardCreditHeader();
    }

    /**
     * Create an instance of {@link CreditCardCreditLine }
     * 
     */
    public CreditCardCreditLine createCreditCardCreditLine() {
        return new CreditCardCreditLine();
    }

    /**
     * Create an instance of {@link ItemReceipt }
     * 
     */
    public ItemReceipt createItemReceipt() {
        return new ItemReceipt();
    }

    /**
     * Create an instance of {@link ItemReceiptHeader }
     * 
     */
    public ItemReceiptHeader createItemReceiptHeader() {
        return new ItemReceiptHeader();
    }

    /**
     * Create an instance of {@link ItemReceiptLine }
     * 
     */
    public ItemReceiptLine createItemReceiptLine() {
        return new ItemReceiptLine();
    }

    /**
     * Create an instance of {@link Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
        return new Employee();
    }

    /**
     * Create an instance of {@link TimeActivity }
     * 
     */
    public TimeActivity createTimeActivity() {
        return new TimeActivity();
    }

    /**
     * Create an instance of {@link EmployeeRef }
     * 
     */
    public EmployeeRef createEmployeeRef() {
        return new EmployeeRef();
    }

    /**
     * Create an instance of {@link SalesOrder }
     * 
     */
    public SalesOrder createSalesOrder() {
        return new SalesOrder();
    }

    /**
     * Create an instance of {@link SalesOrderHeader }
     * 
     */
    public SalesOrderHeader createSalesOrderHeader() {
        return new SalesOrderHeader();
    }

    /**
     * Create an instance of {@link SalesOrderLine }
     * 
     */
    public SalesOrderLine createSalesOrderLine() {
        return new SalesOrderLine();
    }

    /**
     * Create an instance of {@link SalesTaxGroup }
     * 
     */
    public SalesTaxGroup createSalesTaxGroup() {
        return new SalesTaxGroup();
    }

    /**
     * Create an instance of {@link SalesTaxRef }
     * 
     */
    public SalesTaxRef createSalesTaxRef() {
        return new SalesTaxRef();
    }

    /**
     * Create an instance of {@link VendorCreditToApply }
     * 
     */
    public VendorCreditToApply createVendorCreditToApply() {
        return new VendorCreditToApply();
    }

    /**
     * Create an instance of {@link VendorCredit }
     * 
     */
    public VendorCredit createVendorCredit() {
        return new VendorCredit();
    }

    /**
     * Create an instance of {@link VendorCreditHeader }
     * 
     */
    public VendorCreditHeader createVendorCreditHeader() {
        return new VendorCreditHeader();
    }

    /**
     * Create an instance of {@link VendorCreditLine }
     * 
     */
    public VendorCreditLine createVendorCreditLine() {
        return new VendorCreditLine();
    }

    /**
     * Create an instance of {@link CustomFieldDefinitions }
     * 
     */
    public CustomFieldDefinitions createCustomFieldDefinitions() {
        return new CustomFieldDefinitions();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link PaymentHeader }
     * 
     */
    public PaymentHeader createPaymentHeader() {
        return new PaymentHeader();
    }

    /**
     * Create an instance of {@link PaymentLine }
     * 
     */
    public PaymentLine createPaymentLine() {
        return new PaymentLine();
    }

    /**
     * Create an instance of {@link SalesReceipt }
     * 
     */
    public SalesReceipt createSalesReceipt() {
        return new SalesReceipt();
    }

    /**
     * Create an instance of {@link SalesReceiptHeader }
     * 
     */
    public SalesReceiptHeader createSalesReceiptHeader() {
        return new SalesReceiptHeader();
    }

    /**
     * Create an instance of {@link SalesReceiptLine }
     * 
     */
    public SalesReceiptLine createSalesReceiptLine() {
        return new SalesReceiptLine();
    }

    /**
     * Create an instance of {@link Bill }
     * 
     */
    public Bill createBill() {
        return new Bill();
    }

    /**
     * Create an instance of {@link BillHeader }
     * 
     */
    public BillHeader createBillHeader() {
        return new BillHeader();
    }

    /**
     * Create an instance of {@link BillLine }
     * 
     */
    public BillLine createBillLine() {
        return new BillLine();
    }

    /**
     * Create an instance of {@link PaymentMethod }
     * 
     */
    public PaymentMethod createPaymentMethod() {
        return new PaymentMethod();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link CashPurchase }
     * 
     */
    public CashPurchase createCashPurchase() {
        return new CashPurchase();
    }

    /**
     * Create an instance of {@link CashPurchaseHeader }
     * 
     */
    public CashPurchaseHeader createCashPurchaseHeader() {
        return new CashPurchaseHeader();
    }

    /**
     * Create an instance of {@link CashPurchaseLine }
     * 
     */
    public CashPurchaseLine createCashPurchaseLine() {
        return new CashPurchaseLine();
    }

    /**
     * Create an instance of {@link Estimate }
     * 
     */
    public Estimate createEstimate() {
        return new Estimate();
    }

    /**
     * Create an instance of {@link EstimateHeader }
     * 
     */
    public EstimateHeader createEstimateHeader() {
        return new EstimateHeader();
    }

    /**
     * Create an instance of {@link EstimateLine }
     * 
     */
    public EstimateLine createEstimateLine() {
        return new EstimateLine();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link Discount }
     * 
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link ItemGroupComponent }
     * 
     */
    public ItemGroupComponent createItemGroupComponent() {
        return new ItemGroupComponent();
    }

    /**
     * Create an instance of {@link BOMComponent }
     * 
     */
    public BOMComponent createBOMComponent() {
        return new BOMComponent();
    }

    /**
     * Create an instance of {@link SalesTaxPaymentCheck }
     * 
     */
    public SalesTaxPaymentCheck createSalesTaxPaymentCheck() {
        return new SalesTaxPaymentCheck();
    }

    /**
     * Create an instance of {@link SalesTaxPaymentCheckHeader }
     * 
     */
    public SalesTaxPaymentCheckHeader createSalesTaxPaymentCheckHeader() {
        return new SalesTaxPaymentCheckHeader();
    }

    /**
     * Create an instance of {@link SalesTaxPaymentCheckLine }
     * 
     */
    public SalesTaxPaymentCheckLine createSalesTaxPaymentCheckLine() {
        return new SalesTaxPaymentCheckLine();
    }

    /**
     * Create an instance of {@link JournalEntry }
     * 
     */
    public JournalEntry createJournalEntry() {
        return new JournalEntry();
    }

    /**
     * Create an instance of {@link JournalEntryHeader }
     * 
     */
    public JournalEntryHeader createJournalEntryHeader() {
        return new JournalEntryHeader();
    }

    /**
     * Create an instance of {@link JournalEntryLine }
     * 
     */
    public JournalEntryLine createJournalEntryLine() {
        return new JournalEntryLine();
    }

    /**
     * Create an instance of {@link TxnGeneric.Header }
     * 
     */
    public TxnGeneric.Header createTxnGenericHeader() {
        return new TxnGeneric.Header();
    }

    /**
     * Create an instance of {@link SalesTax }
     * 
     */
    public SalesTax createSalesTax() {
        return new SalesTax();
    }

    /**
     * Create an instance of {@link Persons }
     * 
     */
    public Persons createPersons() {
        return new Persons();
    }

    /**
     * Create an instance of {@link CreditMemo }
     * 
     */
    public CreditMemo createCreditMemo() {
        return new CreditMemo();
    }

    /**
     * Create an instance of {@link CreditMemoHeader }
     * 
     */
    public CreditMemoHeader createCreditMemoHeader() {
        return new CreditMemoHeader();
    }

    /**
     * Create an instance of {@link CreditMemoLine }
     * 
     */
    public CreditMemoLine createCreditMemoLine() {
        return new CreditMemoLine();
    }

    /**
     * Create an instance of {@link InventoryAdjustment }
     * 
     */
    public InventoryAdjustment createInventoryAdjustment() {
        return new InventoryAdjustment();
    }

    /**
     * Create an instance of {@link InventoryAdjustmentHeader }
     * 
     */
    public InventoryAdjustmentHeader createInventoryAdjustmentHeader() {
        return new InventoryAdjustmentHeader();
    }

    /**
     * Create an instance of {@link InventoryAdjustmentLine }
     * 
     */
    public InventoryAdjustmentLine createInventoryAdjustmentLine() {
        return new InventoryAdjustmentLine();
    }

    /**
     * Create an instance of {@link Preferences }
     * 
     */
    public Preferences createPreferences() {
        return new Preferences();
    }

    /**
     * Create an instance of {@link SalesRep }
     * 
     */
    public SalesRep createSalesRep() {
        return new SalesRep();
    }

    /**
     * Create an instance of {@link OtherNameRef }
     * 
     */
    public OtherNameRef createOtherNameRef() {
        return new OtherNameRef();
    }

    /**
     * Create an instance of {@link RestResponse }
     * 
     */
    public RestResponse createRestResponse() {
        return new RestResponse();
    }

    /**
     * Create an instance of {@link CompaniesMetaData }
     * 
     */
    public CompaniesMetaData createCompaniesMetaData() {
        return new CompaniesMetaData();
    }

    /**
     * Create an instance of {@link Charge }
     * 
     */
    public Charge createCharge() {
        return new Charge();
    }

    /**
     * Create an instance of {@link ChargeHeader }
     * 
     */
    public ChargeHeader createChargeHeader() {
        return new ChargeHeader();
    }

    /**
     * Create an instance of {@link ChargeLine }
     * 
     */
    public ChargeLine createChargeLine() {
        return new ChargeLine();
    }

    /**
     * Create an instance of {@link Vendor }
     * 
     */
    public Vendor createVendor() {
        return new Vendor();
    }

    /**
     * Create an instance of {@link CompanyMetaData }
     * 
     */
    public CompanyMetaData createCompanyMetaData() {
        return new CompanyMetaData();
    }

    /**
     * Create an instance of {@link Offering }
     * 
     */
    public Offering createOffering() {
        return new Offering();
    }

    /**
     * Create an instance of {@link UOM }
     * 
     */
    public UOM createUOM() {
        return new UOM();
    }

    /**
     * Create an instance of {@link UOMConvUnit }
     * 
     */
    public UOMConvUnit createUOMConvUnit() {
        return new UOMConvUnit();
    }

    /**
     * Create an instance of {@link Organizations }
     * 
     */
    public Organizations createOrganizations() {
        return new Organizations();
    }

    /**
     * Create an instance of {@link PurchaseOrder }
     * 
     */
    public PurchaseOrder createPurchaseOrder() {
        return new PurchaseOrder();
    }

    /**
     * Create an instance of {@link PurchaseOrderHeader }
     * 
     */
    public PurchaseOrderHeader createPurchaseOrderHeader() {
        return new PurchaseOrderHeader();
    }

    /**
     * Create an instance of {@link PurchaseOrderLine }
     * 
     */
    public PurchaseOrderLine createPurchaseOrderLine() {
        return new PurchaseOrderLine();
    }

    /**
     * Create an instance of {@link CreditCardCharge }
     * 
     */
    public CreditCardCharge createCreditCardCharge() {
        return new CreditCardCharge();
    }

    /**
     * Create an instance of {@link CreditCardChargeHeader }
     * 
     */
    public CreditCardChargeHeader createCreditCardChargeHeader() {
        return new CreditCardChargeHeader();
    }

    /**
     * Create an instance of {@link CreditCardChargeLine }
     * 
     */
    public CreditCardChargeLine createCreditCardChargeLine() {
        return new CreditCardChargeLine();
    }

    /**
     * Create an instance of {@link InventoryAdjustments }
     * 
     */
    public InventoryAdjustments createInventoryAdjustments() {
        return new InventoryAdjustments();
    }

    /**
     * Create an instance of {@link CreditCardCredits }
     * 
     */
    public CreditCardCredits createCreditCardCredits() {
        return new CreditCardCredits();
    }

    /**
     * Create an instance of {@link CreditChargeInfo }
     * 
     */
    public CreditChargeInfo createCreditChargeInfo() {
        return new CreditChargeInfo();
    }

    /**
     * Create an instance of {@link Classes }
     * 
     */
    public Classes createClasses() {
        return new Classes();
    }

    /**
     * Create an instance of {@link HeaderPurchase }
     * 
     */
    public HeaderPurchase createHeaderPurchase() {
        return new HeaderPurchase();
    }

    /**
     * Create an instance of {@link VendorCreditsToApply }
     * 
     */
    public VendorCreditsToApply createVendorCreditsToApply() {
        return new VendorCreditsToApply();
    }

    /**
     * Create an instance of {@link Jobs }
     * 
     */
    public Jobs createJobs() {
        return new Jobs();
    }

    /**
     * Create an instance of {@link DateTypeCustomFieldDefinition }
     * 
     */
    public DateTypeCustomFieldDefinition createDateTypeCustomFieldDefinition() {
        return new DateTypeCustomFieldDefinition();
    }

    /**
     * Create an instance of {@link ValueAdj }
     * 
     */
    public ValueAdj createValueAdj() {
        return new ValueAdj();
    }

    /**
     * Create an instance of {@link StringTypeCustomField }
     * 
     */
    public StringTypeCustomField createStringTypeCustomField() {
        return new StringTypeCustomField();
    }

    /**
     * Create an instance of {@link Estimates }
     * 
     */
    public Estimates createEstimates() {
        return new Estimates();
    }

    /**
     * Create an instance of {@link CustomerRef }
     * 
     */
    public CustomerRef createCustomerRef() {
        return new CustomerRef();
    }

    /**
     * Create an instance of {@link Accounts }
     * 
     */
    public Accounts createAccounts() {
        return new Accounts();
    }

    /**
     * Create an instance of {@link SalesTaxCodes }
     * 
     */
    public SalesTaxCodes createSalesTaxCodes() {
        return new SalesTaxCodes();
    }

    /**
     * Create an instance of {@link ItemReceipts }
     * 
     */
    public ItemReceipts createItemReceipts() {
        return new ItemReceipts();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link SalesTaxes }
     * 
     */
    public SalesTaxes createSalesTaxes() {
        return new SalesTaxes();
    }

    /**
     * Create an instance of {@link DateTypeCustomField }
     * 
     */
    public DateTypeCustomField createDateTypeCustomField() {
        return new DateTypeCustomField();
    }

    /**
     * Create an instance of {@link VendorCredits }
     * 
     */
    public VendorCredits createVendorCredits() {
        return new VendorCredits();
    }

    /**
     * Create an instance of {@link CashPurchases }
     * 
     */
    public CashPurchases createCashPurchases() {
        return new CashPurchases();
    }

    /**
     * Create an instance of {@link CreditMemos }
     * 
     */
    public CreditMemos createCreditMemos() {
        return new CreditMemos();
    }

    /**
     * Create an instance of {@link JournalEntries }
     * 
     */
    public JournalEntries createJournalEntries() {
        return new JournalEntries();
    }

    /**
     * Create an instance of {@link Checks }
     * 
     */
    public Checks createChecks() {
        return new Checks();
    }

    /**
     * Create an instance of {@link CheckPayment }
     * 
     */
    public CheckPayment createCheckPayment() {
        return new CheckPayment();
    }

    /**
     * Create an instance of {@link Invoices }
     * 
     */
    public Invoices createInvoices() {
        return new Invoices();
    }

    /**
     * Create an instance of {@link ExternalKey }
     * 
     */
    public ExternalKey createExternalKey() {
        return new ExternalKey();
    }

    /**
     * Create an instance of {@link SalesTaxGroups }
     * 
     */
    public SalesTaxGroups createSalesTaxGroups() {
        return new SalesTaxGroups();
    }

    /**
     * Create an instance of {@link QtyAdj }
     * 
     */
    public QtyAdj createQtyAdj() {
        return new QtyAdj();
    }

    /**
     * Create an instance of {@link SalesReceipts }
     * 
     */
    public SalesReceipts createSalesReceipts() {
        return new SalesReceipts();
    }

    /**
     * Create an instance of {@link NumberTypeCustomFieldDefinition }
     * 
     */
    public NumberTypeCustomFieldDefinition createNumberTypeCustomFieldDefinition() {
        return new NumberTypeCustomFieldDefinition();
    }

    /**
     * Create an instance of {@link LineSales }
     * 
     */
    public LineSales createLineSales() {
        return new LineSales();
    }

    /**
     * Create an instance of {@link TimeActivities }
     * 
     */
    public TimeActivities createTimeActivities() {
        return new TimeActivities();
    }

    /**
     * Create an instance of {@link SalesReps }
     * 
     */
    public SalesReps createSalesReps() {
        return new SalesReps();
    }

    /**
     * Create an instance of {@link StringTypeCustomFieldDefinition }
     * 
     */
    public StringTypeCustomFieldDefinition createStringTypeCustomFieldDefinition() {
        return new StringTypeCustomFieldDefinition();
    }

    /**
     * Create an instance of {@link NumberTypeCustomField }
     * 
     */
    public NumberTypeCustomField createNumberTypeCustomField() {
        return new NumberTypeCustomField();
    }

    /**
     * Create an instance of {@link Bills }
     * 
     */
    public Bills createBills() {
        return new Bills();
    }

    /**
     * Create an instance of {@link CashPayment }
     * 
     */
    public CashPayment createCashPayment() {
        return new CashPayment();
    }

    /**
     * Create an instance of {@link Payments }
     * 
     */
    public Payments createPayments() {
        return new Payments();
    }

    /**
     * Create an instance of {@link Discounts }
     * 
     */
    public Discounts createDiscounts() {
        return new Discounts();
    }

    /**
     * Create an instance of {@link CreditCardCharges }
     * 
     */
    public CreditCardCharges createCreditCardCharges() {
        return new CreditCardCharges();
    }

    /**
     * Create an instance of {@link ShipMethods }
     * 
     */
    public ShipMethods createShipMethods() {
        return new ShipMethods();
    }

    /**
     * Create an instance of {@link PaymentMethods }
     * 
     */
    public PaymentMethods createPaymentMethods() {
        return new PaymentMethods();
    }

    /**
     * Create an instance of {@link HeaderSales }
     * 
     */
    public HeaderSales createHeaderSales() {
        return new HeaderSales();
    }

    /**
     * Create an instance of {@link CompanyPreferences }
     * 
     */
    public CompanyPreferences createCompanyPreferences() {
        return new CompanyPreferences();
    }

    /**
     * Create an instance of {@link ReimbursableInfo }
     * 
     */
    public ReimbursableInfo createReimbursableInfo() {
        return new ReimbursableInfo();
    }

    /**
     * Create an instance of {@link TxnGenerics }
     * 
     */
    public TxnGenerics createTxnGenerics() {
        return new TxnGenerics();
    }

    /**
     * Create an instance of {@link PaymentDetail }
     * 
     */
    public PaymentDetail createPaymentDetail() {
        return new PaymentDetail();
    }

    /**
     * Create an instance of {@link Charges }
     * 
     */
    public Charges createCharges() {
        return new Charges();
    }

    /**
     * Create an instance of {@link CreditChargeResponse }
     * 
     */
    public CreditChargeResponse createCreditChargeResponse() {
        return new CreditChargeResponse();
    }

    /**
     * Create an instance of {@link SalesTerms }
     * 
     */
    public SalesTerms createSalesTerms() {
        return new SalesTerms();
    }

    /**
     * Create an instance of {@link SalesOrders }
     * 
     */
    public SalesOrders createSalesOrders() {
        return new SalesOrders();
    }

    /**
     * Create an instance of {@link Items }
     * 
     */
    public Items createItems() {
        return new Items();
    }

    /**
     * Create an instance of {@link PurchaseOrders }
     * 
     */
    public PurchaseOrders createPurchaseOrders() {
        return new PurchaseOrders();
    }

    /**
     * Create an instance of {@link LineBase }
     * 
     */
    public LineBase createLineBase() {
        return new LineBase();
    }

    /**
     * Create an instance of {@link CreditCardPayment }
     * 
     */
    public CreditCardPayment createCreditCardPayment() {
        return new CreditCardPayment();
    }

    /**
     * Create an instance of {@link Customers }
     * 
     */
    public Customers createCustomers() {
        return new Customers();
    }

    /**
     * Create an instance of {@link HeaderBase }
     * 
     */
    public HeaderBase createHeaderBase() {
        return new HeaderBase();
    }

    /**
     * Create an instance of {@link SalesTaxPaymentChecks }
     * 
     */
    public SalesTaxPaymentChecks createSalesTaxPaymentChecks() {
        return new SalesTaxPaymentChecks();
    }

    /**
     * Create an instance of {@link BooleanTypeCustomFieldDefinition }
     * 
     */
    public BooleanTypeCustomFieldDefinition createBooleanTypeCustomFieldDefinition() {
        return new BooleanTypeCustomFieldDefinition();
    }

    /**
     * Create an instance of {@link UOMs }
     * 
     */
    public UOMs createUOMs() {
        return new UOMs();
    }

    /**
     * Create an instance of {@link Employees }
     * 
     */
    public Employees createEmployees() {
        return new Employees();
    }

    /**
     * Create an instance of {@link TxnRef }
     * 
     */
    public TxnRef createTxnRef() {
        return new TxnRef();
    }

    /**
     * Create an instance of {@link BillPayments }
     * 
     */
    public BillPayments createBillPayments() {
        return new BillPayments();
    }

    /**
     * Create an instance of {@link Vendors }
     * 
     */
    public Vendors createVendors() {
        return new Vendors();
    }

    /**
     * Create an instance of {@link LinePurchase }
     * 
     */
    public LinePurchase createLinePurchase() {
        return new LinePurchase();
    }

    /**
     * Create an instance of {@link BooleanTypeCustomField }
     * 
     */
    public BooleanTypeCustomField createBooleanTypeCustomField() {
        return new BooleanTypeCustomField();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Employee }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.intuit.com/sb/cdm/v2", name = "Employee")
    public JAXBElement<Employee> createEmployee(Employee value) {
        return new JAXBElement<Employee>(_Employee_QNAME, Employee.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.intuit.com/sb/cdm/v2", name = "Organization")
    public JAXBElement<Organization> createOrganization(Organization value) {
        return new JAXBElement<Organization>(_Organization_QNAME, Organization.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomFieldDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.intuit.com/sb/cdm/v2", name = "CustomFieldDefinition")
    public JAXBElement<CustomFieldDefinition> createCustomFieldDefinition(CustomFieldDefinition value) {
        return new JAXBElement<CustomFieldDefinition>(_CustomFieldDefinition_QNAME, CustomFieldDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomField }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.intuit.com/sb/cdm/v2", name = "CustomField")
    public JAXBElement<CustomField> createCustomField(CustomField value) {
        return new JAXBElement<CustomField>(_CustomField_QNAME, CustomField.class, null, value);
    }

}
