//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.03 at 03:30:34 PM EDT 
//


package com.intuit.sb.cdm.v2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OtherNameRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherNameRef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.intuit.com/sb/cdm/v2}OtherNameReferenceGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherNameRef", propOrder = {
    "otherNameId",
    "otherNameName"
})
public class OtherNameRef
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "OtherNameId")
    protected IdType otherNameId;
    @XmlElement(name = "OtherNameName")
    protected String otherNameName;

    /**
     * Gets the value of the otherNameId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getOtherNameId() {
        return otherNameId;
    }

    /**
     * Sets the value of the otherNameId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setOtherNameId(IdType value) {
        this.otherNameId = value;
    }

    /**
     * Gets the value of the otherNameName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherNameName() {
        return otherNameName;
    }

    /**
     * Sets the value of the otherNameName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherNameName(String value) {
        this.otherNameName = value;
    }

}
