//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.03 at 03:30:34 PM EDT 
//


package com.intuit.sb.cdm.v2;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information that pertains to the entire Payment
 * 
 * <p>Java class for PaymentHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentHeader">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}HeaderBase">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}CustomerReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}JobReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}RemitToReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}ARAccountReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}DepositToAccountReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}PaymentMethodReferenceGroup" minOccurs="0"/>
 *         &lt;element name="Detail" type="{http://www.intuit.com/sb/cdm/v2}PaymentDetail" minOccurs="0"/>
 *         &lt;element name="TotalAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="UnappliedAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ProcessPayment" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentHeader", propOrder = {
    "customerId",
    "customerName",
    "jobId",
    "jobName",
    "remitToId",
    "remitToName",
    "arAccountId",
    "arAccountName",
    "depositToAccountId",
    "depositToAccountName",
    "paymentMethodId",
    "paymentMethodName",
    "detail",
    "totalAmt",
    "unappliedAmt",
    "processPayment"
})
public class PaymentHeader
    extends HeaderBase
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CustomerId")
    protected IdType customerId;
    @XmlElement(name = "CustomerName")
    protected String customerName;
    @XmlElement(name = "JobId")
    protected IdType jobId;
    @XmlElement(name = "JobName")
    protected String jobName;
    @XmlElement(name = "RemitToId")
    protected IdType remitToId;
    @XmlElement(name = "RemitToName")
    protected String remitToName;
    @XmlElement(name = "ARAccountId")
    protected IdType arAccountId;
    @XmlElement(name = "ARAccountName")
    protected String arAccountName;
    @XmlElement(name = "DepositToAccountId")
    protected IdType depositToAccountId;
    @XmlElement(name = "DepositToAccountName")
    protected String depositToAccountName;
    @XmlElement(name = "PaymentMethodId")
    protected IdType paymentMethodId;
    @XmlElement(name = "PaymentMethodName")
    protected String paymentMethodName;
    @XmlElement(name = "Detail")
    protected PaymentDetail detail;
    @XmlElement(name = "TotalAmt")
    protected BigDecimal totalAmt;
    @XmlElement(name = "UnappliedAmt")
    protected BigDecimal unappliedAmt;
    @XmlElement(name = "ProcessPayment")
    protected Boolean processPayment;

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setCustomerId(IdType value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the jobId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getJobId() {
        return jobId;
    }

    /**
     * Sets the value of the jobId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setJobId(IdType value) {
        this.jobId = value;
    }

    /**
     * Gets the value of the jobName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * Sets the value of the jobName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobName(String value) {
        this.jobName = value;
    }

    /**
     * Gets the value of the remitToId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getRemitToId() {
        return remitToId;
    }

    /**
     * Sets the value of the remitToId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setRemitToId(IdType value) {
        this.remitToId = value;
    }

    /**
     * Gets the value of the remitToName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemitToName() {
        return remitToName;
    }

    /**
     * Sets the value of the remitToName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemitToName(String value) {
        this.remitToName = value;
    }

    /**
     * Gets the value of the arAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getARAccountId() {
        return arAccountId;
    }

    /**
     * Sets the value of the arAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setARAccountId(IdType value) {
        this.arAccountId = value;
    }

    /**
     * Gets the value of the arAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARAccountName() {
        return arAccountName;
    }

    /**
     * Sets the value of the arAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARAccountName(String value) {
        this.arAccountName = value;
    }

    /**
     * Gets the value of the depositToAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getDepositToAccountId() {
        return depositToAccountId;
    }

    /**
     * Sets the value of the depositToAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setDepositToAccountId(IdType value) {
        this.depositToAccountId = value;
    }

    /**
     * Gets the value of the depositToAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositToAccountName() {
        return depositToAccountName;
    }

    /**
     * Sets the value of the depositToAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositToAccountName(String value) {
        this.depositToAccountName = value;
    }

    /**
     * Gets the value of the paymentMethodId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getPaymentMethodId() {
        return paymentMethodId;
    }

    /**
     * Sets the value of the paymentMethodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setPaymentMethodId(IdType value) {
        this.paymentMethodId = value;
    }

    /**
     * Gets the value of the paymentMethodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMethodName() {
        return paymentMethodName;
    }

    /**
     * Sets the value of the paymentMethodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethodName(String value) {
        this.paymentMethodName = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetail }
     *     
     */
    public PaymentDetail getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetail }
     *     
     */
    public void setDetail(PaymentDetail value) {
        this.detail = value;
    }

    /**
     * Gets the value of the totalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAmt() {
        return totalAmt;
    }

    /**
     * Sets the value of the totalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAmt(BigDecimal value) {
        this.totalAmt = value;
    }

    /**
     * Gets the value of the unappliedAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnappliedAmt() {
        return unappliedAmt;
    }

    /**
     * Sets the value of the unappliedAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnappliedAmt(BigDecimal value) {
        this.unappliedAmt = value;
    }

    /**
     * Gets the value of the processPayment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProcessPayment() {
        return processPayment;
    }

    /**
     * Sets the value of the processPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProcessPayment(Boolean value) {
        this.processPayment = value;
    }

}
